### ISSUE TITLE
Same day event

### ISSUE THREAD

**Issue by ericchernuka** [iainbeeston/nickel#4]
I have a use case for a same day event and parsing it without context of a future date.  This would be more akin to how Google Calendar works when you are creating an event on a specific day.

``` ruby
n = Nickel.parse("meeting with Jimmy at 7am", Time.now)
n.message                       #=> "meeting with Jimmy"
n.occurrences.first.start_date  #=> "20140207"
n.occurrences.first.start_time  #=> "070000"
```

**Comment by mwlang** [comment]
related to #31 

Is this project active?
